version: "3.9"

services:
  # 🐍 FastAPI + ROFL
  rofl:
    build:
      context: ./rofl
    ports:
      - "8000:8000"
    volumes:
      - ./rofl:/app           # hot-reload when you edit app.py
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  # ⚛️ Next.js dev server
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app       # live-reload on file changes
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - ROFL_URL=http://rofl:8000
    depends_on:
      - rofl
